name: Publish Tweet-CLI-V2 Package
on:
  release:
    types: [created, ]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: https://registry.npmjs.org/

      - run: |
          git config user.email '${{ secrets.GIT_USER_EMAIL }}'
          git config user.name '${{ secrets.GIT_USER_NAME }}'

      # --- Prefiero hacerlo manualmente ---
      # - run: npm version patch
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}